//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoVoyage.Donnees
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierVoyageur
    {
        public long id { get; set; }
        public System.Guid Voyageur { get; set; }
        public System.Guid Dossier { get; set; }
    
        public virtual Dossier Dossier1 { get; set; }
        public virtual Voyageur Voyageur1 { get; set; }
    }
}
